### ISSUE TITLE
Default value for removed image is different from an image that was never set

### ISSUE THREAD

**Issue by Bibendus83** [qcod/laravel-app-settings#31]
I noticed that calling `setting('img_setting', 'default_img')` has a different behavior depending if the value has never been set or if the value has been set and then the image has been removed later.
In the first case `default_img` is returned, in the second one `null` is returned.
I think that in both cases `default_img` should be returned.

**Comment by hellodit** [comment]
It's fixed now? 
I try to call image settings, but it has not called the value

**Comment by Bibendus83** [comment]
> 
> 
> It's fixed now?
> I try to call image settings, but it has not called the value

I don't see any fix on the repository, I still have the problem.

**Comment by Bibendus83** [comment]
The solution is to change the
`$this->set($settingName, null);`
line in uploadFile
to
`$this->remove($settingName);`
